# Cross manifest file for cross compiling and testing Rust code.
#
# For more information, visit https://github.com/rust-embedded/cross.

[build.env]
passthrough = [
    "RUST_BACKTRACE",
]

[target.aarch64-unknown-linux-gnu]
image = "wolfgangwazzlestrauss/cross-sampitor:aarch64-unknown-linux-gnu"

[target.armv7-unknown-linux-gnueabihf]
image = "wolfgangwazzlestrauss/cross-sampitor:armv7-unknown-linux-gnueabihf"
