# Project task definition file for Cargo Make. 
#
# For more information, visit https://github.com/sagiegurari/cargo-make.

[tasks.all]
dependencies = [
    "format",
    "lint",
    "document",
    "test",
    "cross",
    "tarpaulin",
    "bench"
]

[tasks.cross]
dependencies = ["docker"]
install_crate = "cross"
script = { file = "scripts/cross_test.rs" }
script_runner = "@rust"

[tasks.docker]
script_runner = "@rust"
script = { file = "scripts/build_images.rs" }

[tasks.document]
args = ["doc"]
command = "cargo"

[tasks.format]
args = ["fmt", "--", "--check"]
command = "cargo"
install_crate = "rustfmt"

[tasks.lint]
args = [
    "clippy",
    "--all",
    "--",
    "-D",
    "clippy::all",
    "-D",
    "clippy::cargo",
    "-D",
    "clippy::nursery",
    "-D",
    "clippy::pedantic",
    "-A",
    "clippy::cast-possible-truncation",
    "-A",
    "clippy::cast-precision-loss",
    "-D",
    "warnings"
]
command = "cargo"
install_crate = "clippy"

# Task cannot be named coverage, since cargo-make has a predefined coverage
# task.
[tasks.tarpaulin]
args = ["tarpaulin", "-v", "--ignore-tests", "--out", "Lcov"]
command = "cargo"
condition = { platforms = ["linux"] }
install_crate = "tarpaulin"

[tasks.test]
args = ["test"]
command = "cargo"
