# Project task definition file for Cargo Make. 
#
# For more information, visit https://github.com/sagiegurari/cargo-make.

[tasks.all]
dependencies = [
    "format",
    "lint",
    "test",
    "cross",
    "tarpaulin"
]

[tasks.cross]
args = ["test", "--target", "aarch64-unknown-linux-gnu"]
command = "cross"
dependencies = ["docker"]
install_crate = "cross"

[tasks.docker]
args = [
    "build",
    "-f",
    "docker/Dockerfile.aarch64-unknown-linux-gnu",
    "-t",
    "wolfgangwazzlestrauss/cross-sampitor:aarch64-unknown-linux-gnu",
    "."
]
command = "docker"

[tasks.format]
args = ["fmt", "--", "-l", "--emit", "files"]
command = "cargo"
install_crate = "rustfmt"

[tasks.lint]
args = [
    "clippy",
    "--all",
    "--",
    "-D",
    "clippy::all",
    "-D",
    "clippy::nursery",
    "-D",
    "clippy::pedantic",
    "-A",
    "clippy::cast-lossless",
    "-A",
    "clippy::cast-possible-truncation",
    "-A",
    "clippy::cast-precision-loss",
    "-A",
    "clippy::cast-sign-loss"
]
command = "cargo"
install_crate = "clippy"

# Task cannot be named coverage, since cargo-make has a predefined coverage
# task.
[tasks.tarpaulin]
args = ["tarpaulin", "-v", "--ignore-tests", "--out", "Lcov"]
command = "cargo"
condition = { platforms = ["linux"] }
install_crate = "tarpaulin"

[tasks.test]
args = ["test"]
command = "cargo"
