# Project task definition file for Cargo Make. 
#
# For more information, visit https://github.com/sagiegurari/cargo-make.

[tasks.all]
dependencies = [
    "format",
    "build",
    "test"
]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

# Only run on x86_64 Linux.
[tasks.test-coverage]
command = "cargo"
args = ["tarpaulin", "-v", "--ignore-tests", "--out", "Lcov"]
dependencies = ["clean"]
