# Project task definition file for Cargo Make. 
#
# For more information, visit https://github.com/sagiegurari/cargo-make.

[tasks.all]
dependencies = [
    "format",
    "lint",
    "test",
    "cross",
    "coverage"
]

[tasks.coverage]
args = ["tarpaulin", "-v", "--ignore-tests", "--out", "Lcov"]
command = "cargo"
condition = { platforms = ["linux"] }

[tasks.cross]
args = ["test", "--target", "aarch64-unknown-linux-gnu"]
command = "cross"
dependencies = ["docker"]
install_crate = "cross"

[tasks.docker]
args = [
    "build",
    "-f",
    "docker/Dockerfile.aarch64-unknown-linux-gnu",
    "-t",
    "wolfgangwazzlestrauss/cross-sampitor:aarch64-unknown-linux-gnu",
    "."
]
command = "docker"

[tasks.format]
args = ["fmt", "--", "-l", "--emit", "files"]
command = "cargo"
install_crate = "rustfmt"

[tasks.lint]
args = ["clippy"]
command = "cargo"
install_crate = "clippy"

[tasks.test]
args = ["test"]
command = "cargo"
