# Rustc toolchain override file.
#
# Is currently not named rust-toolchain.toml, since
# https://github.com/marketplace/actions/rust-toolchain does not yet support the
# new name. For more information, visit
# https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file.

[toolchain]
channel = "stable"
components = ["clippy", "rustfmt"]
