# Rustc toolchain override file.
#
# For more information, visit
# https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file.

[toolchain]
channel = "stable"
components = ["clippy", "rustfmt"]
