FROM rustembedded/cross:armv7-unknown-linux-gnueabihf-0.2.1

# Enable Rust pkg-config cross compilation support.
#
# For more information, visit https://github.com/rust-lang/pkg-config-rs.
ENV PKG_CONFIG_ALLOW_CROSS 1
ENV PKG_CONFIG_PATH /usr/lib/arm-linux-gnueabihf/pkgconfig/

# Update accepted package architecture list.
#
# Flags:
#   -m: Ignore missing packages and handle result.
#   -q: Produce log suitable output by omitting progress indicators.
#   --add-architecture <arch>: Add <arch> to the accepted list of package 
#     architectures.
RUN dpkg --add-architecture armhf \
    && apt-get update -qm

# Install ARMV7 audio libraries.
#
# Flags:
#   -q: Produce log suitable output by omitting progress indicators.
#   -y: Assume "yes" as answer to all prompts and run non-interactively.
RUN apt-get install -qy \
    libasound2-dev:armhf
