# GitHub Actions workflow file.
#
# For more information, visit
# https://docs.github.com/actions/learn-github-actions.

name: build

# Trigger workflow on any push or pull request.
on:
  - pull_request
  - push

jobs:
  lint:
    name: Check code with formatter and linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
      - name: Install Node interpreter
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Prettier formatter
        run: |
          npm install -g prettier
      - name: Check configuration file formatting
        run: |
          prettier --check .
      - name: Install ALSA packages
        run: |
          sudo apt-get update
          sudo apt-get install -y alsa-utils libasound2-dev
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          components: clippy, rustfmt
          toolchain: stable
      - name: Install Rust packages from cache
        uses: swatinem/rust-cache@v1
      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          args: cargo-make
          command: install
      - name: Check code formatting
        uses: actions-rs/cargo@v1
        with:
          args: format
          command: fmt
      - name: Run Rust code linters
        uses: actions-rs/cargo@v1
        with:
          args: lint
          command: make

  test:
    # GitHub contains function does not support literal arrays. For more
    # information, visit
    # https://github.community/t/passing-an-array-literal-to-contains-function-causes-syntax-error/17213.
    if: >-
      ${{ contains(fromJson('["refs/head/develop", "refs/head/main",
      "refs/head/master"]'), github.ref) }}
    name: Run test suite for Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
      - name: Install ALSA packages
        if: matrix.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y alsa-utils libasound2-dev
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Rust packages from cache
        uses: swatinem/rust-cache@v1
      - name: Run Rust tests
        env:
          RUST_BACKTRACE: 1
        uses: actions-rs/cargo@v1
        with:
          command: test
