# GitHub Actions workflow file.
#
# For more information, visit
# https://docs.github.com/actions/learn-github-actions.

name: build

# Trigger workflow on any push or pull request.
on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "**"

jobs:
  check:
    name: Check that code compiles over multiple Rust versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
      - name: Install ALSA packages
        run: |
          sudo apt-get update
          sudo apt-get install -y alsa-utils libasound2-dev
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          components: clippy, rustfmt
          toolchain: stable
      - name: Install Rust packages from cache
        uses: swatinem/rust-cache@v2
      - name: Install cargo-make
        uses: davidB/rust-cargo-make@v1
      - name: Run Rust code linters
        uses: actions-rs/cargo@v1
        with:
          args: check
          command: make

  lint:
    name: Check code with formatter and linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
      - name: Install Node interpreter
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Prettier formatter
        run: npm install -g prettier
      - name: Check configuration file formatting
        run: prettier --check .
      - name: Install ALSA packages
        run: |
          sudo apt-get update
          sudo apt-get install -y alsa-utils libasound2-dev
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          components: clippy, rustfmt
          toolchain: stable
      - name: Install Rust packages from cache
        uses: swatinem/rust-cache@v2
      - name: Install cargo-make
        uses: davidB/rust-cargo-make@v1
      - name: Check code formatting
        uses: actions-rs/cargo@v1
        with:
          args: format
          command: make
      - name: Run Rust code linters
        uses: actions-rs/cargo@v1
        with:
          args: lint
          command: make

  test:
    # GitHub contains function does not support literal arrays. For more
    # information, visit
    # https://github.community/t/passing-an-array-literal-to-contains-function-causes-syntax-error/17213.
    if: >-
      ${{ !contains(fromJson('["refs/heads/develop", "refs/heads/main",
      "refs/heads/master"]'), github.ref) }}
    name: Run test suite for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
      - name: Install ALSA packages
        run: |
          sudo apt-get update
          sudo apt-get install -y alsa-utils libasound2-dev
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Rust packages from cache
        uses: swatinem/rust-cache@v2
      - name: Run Rust tests
        env:
          RUST_BACKTRACE: 1
        uses: actions-rs/cargo@v1
        with:
          command: test
