# GitHub Actions workflow file.
#
# For more information, visit
# https://docs.github.com/actions/learn-github-actions.

name: build

# Make workflow run only for commits pushed to othe develop, feature, master
# branches, or pull requests made to the develop and master branches.
on:
  push:
    branches:
      - develop
      - feature/*
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  lint:
    name: Lint and format code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
      - name: Install Node interpreter
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Prettier formatter
        run: |
          npm install -g prettier
      - name: Check configuration file formatting
        run: |
          prettier --check .
      - name: Install ALSA packages
        run: sudo apt-get install -y alsa-utils libasound2-dev
      - name: Install latest stable Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          components: clippy, rustfmt
          toolchain: stable
      - name: Check code formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
      # Does not use dependency caching since Clippy may not work correctly with
      # cached dependencies. See
      # https://github.com/rust-lang/rust-clippy/issues/4612 for details.
      - name: Run Rust code linters
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  test:
    name: Run tests for ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [Linux, MacOS, Windows]
        include:
          - os: Linux
            runner: ubuntu-latest
          - os: MacOS
            runner: macos-latest
          - os: Windows
            runner: windows-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
      - name: Install ALSA packages
        if: matrix.os == 'Linux'
        run: sudo apt-get install -y alsa-utils libasound2-dev
      - name: Install latest stable Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Download dependency cache
        uses: swatinem/rust-cache@v1
      - name: Run Rust tests
        uses: actions-rs/cargo@v1
        with:
          command: test

  coverage:
    name: Check code for test coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
      - name: Install ALSA packages
        run: sudo apt-get install -y alsa-utils libasound2-dev
      - name: Install latest stable Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Download dependency cache
        uses: swatinem/rust-cache@v1
      - name: Run test code coverage
        uses: actions-rs/tarpaulin@v0.1

  benchmark:
    name: Check for benchmark performance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
      - name: Install ALSA packages
        run: sudo apt-get install -y alsa-utils libasound2-dev
      - name: Install latest stable Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Download dependency cache
        uses: swatinem/rust-cache@v1
      - name: Run benchmark suite
        uses: actions-rs/cargo@v1
        with:
          command: bench
