# GitHub Actions workflow file.
#
# For more information, visit
# https://docs.github.com/actions/learn-github-actions.

name: pages

# Make workflow run only for commits pushed or pull requests made to the
# develop, main, and master branches.
on:
  push:
    branches:
      - main
      - master

jobs:
  docs:
    name: Build and publish documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
      - name: Install ALSA packages
        run: sudo apt-get install -y alsa-utils libasound2-dev
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Rust packages from cache
        uses: swatinem/rust-cache@v1
      - name: Build documentation
        uses: actions-rs/cargo@v1
        with:
          command: doc
      # Cargo doc does not produce a root index.html page.
      - name: Add HTML root redirect page
        run: |
          printf '<head><meta http-equiv="refresh" content="0; url=sampitor/index.html" /></head>' > target/doc/index.html
      - name: Publish documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/doc
